Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/pudb/__init__.py", line 77, in runscript
    dbg._runscript(mainpyfile)
  File "/home/user/.local/lib/python2.7/site-packages/pudb/debugger.py", line 419, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "Lotto.py", line 26, in <module>
    if data_from_json[0] == nick:
IndexError: list index out of range
